"""Generate exact line locations for source declarations.

File map: DECLARATION_PATTERNS recognizes Rust/Python declarations; discover_files
selects owned code; declarations extracts line numbers; main writes docs/code-index.md.
Variables: ROOT anchors paths, OUTPUT names the generated report, and patterns define
the intentionally small declaration grammar.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "code-index.md"
DECLARATION_PATTERNS = {
    ".rs": re.compile(
        r"^\s*(?:pub(?:\([^)]*\))?\s+)?(?:const\s+)?(?:async\s+)?"
        r"(?P<kind>fn|struct|enum|trait|mod)\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)"
    ),
    ".py": re.compile(
        r"^\s*(?P<kind>def|class)\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)"
    ),
}


def discover_files() -> list[Path]:
    """Return source and test files in stable repository-relative order."""
    files = [*ROOT.glob("src/**/*.rs"), *ROOT.glob("tests/**/*.rs")]
    files.extend(ROOT.glob("scripts/*.py"))
    return sorted(files, key=lambda path: path.relative_to(ROOT).as_posix())


def declarations(path: Path) -> list[tuple[int, str, str]]:
    """Extract one-based line numbers, declaration kinds, and names from a file."""
    pattern = DECLARATION_PATTERNS[path.suffix]
    found: list[tuple[int, str, str]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        match = pattern.match(line)
        if match:
            found.append((line_number, match.group("kind"), match.group("name")))
    return found


def main() -> None:
    """Write a deterministic Markdown index containing current declaration locations."""
    lines = [
        "# Code index",
        "",
        "Generated by `scripts/generate_code_index.py`; do not edit by hand. Line numbers",
        "are refreshed in CI so file headers can remain useful as implementations evolve.",
        "",
    ]
    for path in discover_files():
        relative = path.relative_to(ROOT).as_posix()
        lines.extend((f"## `{relative}`", "", "| Line | Kind | Name |", "| ---: | --- | --- |"))
        entries = declarations(path)
        if entries:
            lines.extend(f"| {line} | `{kind}` | `{name}` |" for line, kind, name in entries)
        else:
            lines.append("| — | — | No declarations |")
        lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()

